[project]
name = "anonymous"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aamiroo", email = "a.a.drv73358@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.14.0",
    "ruff>=0.16.7",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
anonymous = "anonymous:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]

[tool.ruff.lint]
ignore = ["B008"]